# Site settings
title: Apuntes de HTML y CSS
email: wilder.code.27@gmail.com
description: Sitio de mis apuntes de HTML y CSS
collections:
  pages:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
defaults:
- scope:
    path: _pages
    type: pages
  values:
    layout: pages
- scope:
    path: _posts
    type: posts
  values:
    layout: posts

theme: jekyll-theme-midnight
